engines:
  rubocop:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
exclude_paths:
- test/
- config/
- db/
- .rubocop.yml